### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by alvolate** [MLDSAI/puterbot#3]
Building wheels for collected packages: pynput
  Building wheel for pynput (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynput
  Running setup.py clean for pynput
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pynput
Failed to build pynput
Installing collected packages: wcwidth, pytz, pyrect, pyperclip, pure-eval, ptyprocess, pickleshare, executing, backcall, appnope, altgraph, tzdata, typing-extensions, traitlets, tqdm, tornado, tomli, termcolor, six, PyYAML, pyparsing, pyobjc-core, pyinstaller-hooks-contrib, pygments, pygetwindow, py, prompt-toolkit, pluggy, pillow, pexpect, parso, packaging, ordered-set, numpy, mss, MarkupSafe, macholib, loguru, kiwisolver, iniconfig, greenlet, fonttools, decorator, cycler, clipboard, attrs, sqlalchemy, scipy, python-dateutil, pytest, pyobjc-framework-Cocoa, pyinstaller, matplotlib-inline, Mako, Jinja2, jedi, fire, deepdiff, contourpy, asttokens, stack-data, pyobjc-framework-Quartz, pandas, matplotlib, dictalchemy3, bokeh, alembic, pyobjc-framework-ApplicationServices, ipython, pynput, ipdb
  Running setup.py install for pynput ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pynput did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/taeyangkim/PAT/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/sz/cmfct53971d47n8gp7wk77280000gn/T/pip-req-build-hwg9sldu/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pynput

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by abrichr** [comment]
Thank you! Fixed in https://github.com/MLDSAI/puterbot/commit/3e531fc68f67b32b26e74b76993fb88aab5ad934
